"D:\Program Files\VirtualDub\vdub64.exe" /s v1.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v2.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v3.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v4.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v5.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v6.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v7.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v8.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v9.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v10.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v11.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v12.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v13.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v14.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v15.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v16.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v17.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v18.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v19.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v20.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v21.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v22.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v23.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v24.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v25.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v26.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v27.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v28.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v29.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v30.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v31.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v32.vdscript
