"D:\Program Files\VirtualDub\vdub64.exe" /s v33.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v34.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v35.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v36.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v37.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v38.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v39.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v40.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v41.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v42.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v43.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v44.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v45.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v46.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v47.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v48.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v49.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v50.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v51.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v52.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v53.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v54.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v55.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v56.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v57.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v58.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v59.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v60.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v61.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v62.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v63.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v64.vdscript
