"D:\Program Files\VirtualDub\vdub64.exe" /s v65.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v66.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v67.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v68.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v69.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v70.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v71.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v72.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v73.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v74.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v75.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v76.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v77.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v78.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v79.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v80.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v81.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v82.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v83.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v84.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v85.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v86.vdscript
"D:\Program Files\VirtualDub\vdub64.exe" /s v87.vdscript
